name: Go
on: [push, pull_request]
jobs:
  windows:
      runs-on: windows-latest
      strategy:
        matrix:
          go: ['1.12']
      name: Go ${{ matrix.go }} on Windows
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Build
          shell: bash
          run: |
            go build -v ./testapp

        - name: Test
          shell: cmd
          run: |
            echo ::add-path::C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE
            echo ::add-path::C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN
            echo ::set-env name=LIB::C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;%LIB%
            echo ::set-env name=LIB::C:\Program Files (x86)\Microsoft SDKs\Windows\v6.0A\Lib;%LIB%
            echo ::set-env name=LIB::C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Lib;%LIB%
            echo ::set-env name=INCLUDE::C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include;%INCLUDE%
            dumpbin /exports testapp.exe

  macos:
      runs-on: macOS-latest
      strategy:
        matrix:
          go: ['1.12']
      name: Go ${{ matrix.go }} on MacOS
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Build
          run: |
            go build -v ./testapp
